name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code with Dart Analyzer
        run: flutter analyze
