name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code with Dart Analyzer
        run: flutter analyze

  reachable_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: hash-checker/dart_links_reachable
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: 2.18.0
      - name: Install dependencies
        run: dart pub get

  mobx_validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: hash-checker/flutter_mobx_structure_validator
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: 2.18.0
      - name: Install dependencies
        run: dart pub get
